DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS solves;
DROP TABLE IF EXISTS weapons;
DROP TABLE IF EXISTS victims;
DROP TABLE IF EXISTS locations;

CREATE TABLE sessions (
	id		VARCHAR(5) PRIMARY KEY,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cases (
	id			VARCHAR(6) PRIMARY KEY,
	player_name	VARCHAR(50),
	session		VARCHAR(5),
	color		VARCHAR(10) NOT NULL,
	weapon_id	INT NOT NULL,
	victim_id	INT NOT NULL,
	location_id	INT NOT NULL,
	anon_tokens INT NOT NULL,
	poll_imm	BOOLEAN DEFAULT false,
	penalties	INT NOT NULL DEFAULT 0
);

CREATE TABLE solves (
	id			BIGSERIAL PRIMARY KEY,
	case_id		VARCHAR(6) NOT NULL,
	player_case	VARCHAR(6) NOT NULL,
	first		BOOLEAN
);

CREATE TABLE weapons (
	id		INT PRIMARY KEY,
	name	VARCHAR(50) NOT NULL,
	tag1	VARCHAR(50) NOT NULL,
	tag2	VARCHAR(50) NOT NULL
);

CREATE TABLE victims (
	id		INT PRIMARY KEY,
	name	VARCHAR(50) NOT NULL,
	tag1	VARCHAR(50) NOT NULL,
	tag2	VARCHAR(50) NOT NULL
);

CREATE TABLE locations (
	id		INT PRIMARY KEY,
	name	VARCHAR(50) NOT NULL,
	tag1	VARCHAR(50) NOT NULL,
	tag2	VARCHAR(50) NOT NULL
);
